FROM jenkins/inbound-agent:3248.v65ecb_254c298-5-jdk21 AS main

USER root
RUN set -ex \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y tar podman skopeo \
    && ln -s $(which podman) /usr/bin/docker \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
USER jenkins

FROM main AS agent
USER root
